### ISSUE TITLE
X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 2 at size 5 could not be loaded

### ISSUE THREAD

**Issue by mpaya** [martahidalgo/hipathia#2]
While using functions `multiple_pca_plot` and `pathway_comparison_plot` I found similar errors to the one in the title. This can be solved by installing some packages and rebooting the system.
```bash
sudo apt-get install t1-xfree86-nonfree ttf-xfree86-nonfree ttf-xfree86-nonfree-syriac xfonts-75dpi xfonts-100dpi
```
Maybe it's worth mentioning as Troubleshooting in the Documentation.

**Comment by martahidalgo** [comment]
Thank you @mpaya , we will have it in mind
